
#ifndef _COMMON_H_
#define _COMMON_H_

#ifdef wagic
#define PSP_CTRL_UP JGE_BTN_UP
#define PSP_CTRL_DOWN JGE_BTN_DOWN
#define PSP_CTRL_RIGHT JGE_BTN_RIGHT
#define PSP_CTRL_LEFT JGE_BTN_LEFT
#define PSP_CTRL_CROSS JGE_BTN_SEC
#define PSP_CTRL_CIRCLE JGE_BTN_OK
#define PSP_CTRL_TRIANGLE JGE_BTN_CANCEL
#else
#define JGE_BTN_UP PSP_CTRL_UP
#define JGE_BTN_DOWN PSP_CTRL_DOWN
#define JGE_BTN_RIGHT PSP_CTRL_RIGHT
#define JGE_BTN_LEFT PSP_CTRL_LEFT
#define JGE_BTN_OK PSP_CTRL_CIRCLE
#define JGE_BTN_SEC PSP_CTRL_CROSS
#define JGE_BTN_CANCEL PSP_CTRL_TRIANGLE
#endif

#endif
